# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.0

pipelines:
  default:
    - step:
        name: Run NPM Install
        caches:
          - node
        script: 
          - npm install
    - step:
        name: Run Node Tests
        caches:
          - node
        script:
          - npm test
    - step:
        name: Build Docker Image
        image: atlassian/pipelines-awscli
        script:
          - echo $(aws ecr get-login --no-include-email --region us-west-2)  > login.sh

          - sh login.sh

          - docker build -t $DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} .

          - docker tag $DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT} $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}

          - docker push $DOCKER_ECR_REPO_URL/$DOCKER_IMAGE_NAME:${BITBUCKET_COMMIT}

options:
  docker: true